---
kind: pipeline
type: docker
trigger:
  ref:
    - refs/pull/**
    - refs/tags/*
steps:
  - name: install
    image: node:18
    commands:
      - npm ci
  - name: lint
    image: node:18
    commands:
      - npm run lint
    depends_on:
      - install
  - name: typecheck
    image: node:18
    commands:
      - npm run typecheck
    depends_on:
      - install
  - name: build_npm
    image: node:18
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - npm run build
      - npm set registry https://registry.npmjs.org
      - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
      - npm publish
    when:
      status:
        - success
      event:
        - tag
    depends_on:
      - lint
      - typecheck
  - name: build_docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password
      repo: gergof/signo
      autotag: true
      tags:
        - latest
        - ${DRONE_TAG}
    when:
      status:
        - success
      event:
        - tag
    depends_on:
      - lint
      - typecheck
---
kind: signature
hmac: 8b8f80e8d3ccbd1e8ee4bda6d5b90e33321bae82f06b5560f997dcd037c31c61

...
